apiVersion: v1
kind: Secret
metadata:
  name: mysql-credentials
type: Opaque
data:
  MYSQL_USER: c2ltb24=
  MYSQL_PASSWORD: U2ltb25fNzk4

---

apiVersion: v1
kind: Secret
metadata:
  name: mysql-root-credentials
type: Opaque
data:
  username: cm9vdA==
  MYSQL_ROOT_PASSWORD: cm9vdA==